#!/usr/bin/env ruby

Signal.trap("INT") { exit 1 }

require "pastel"
require "optparse"

# Return an unescaped version of delimiter
#
# @example
#   unescape("foo\\nbar") => "foo\nbar"
#
def unescape(str)
  escable = {
    '\n' => "\n",
    '\r' => "\r",
    '\t' => "\t",
    '\f' => "\f",
    '\v' => "\v"
  }
  str.gsub(/\\[nrtfv]/) { |m| escable[m] }
end

options = {}

ARGV << "-h" if ARGV.empty?

parser = OptionParser.new do |opts|
  opts.on("-d delim", "Specifies character to use to split input coloring") do |val|
    val = val[1..-1] if val.start_with?("=")
    options[:eachline] = unescape(val)
  end

  opts.on("-f", "--force", "Forces string coloring regardless of terminal support") do
    options[:enabled] = true
  end

  opts.on("-s", "--styles", "Prints all available color and style names") do
    ops = (ARGV.include?("--force") || ARGV.include?("-f")) ? {enabled: true} : {}
    ops.merge!(options)
    pastel = Pastel.new(**ops)
    puts "Swatch    Name"
    pastel.styles.keys.each do |name|
      next if %i[clear reset].include?(name)
      puts "%s  %s" % [pastel.decorate("◼ pastel", name), name]
    end
    exit
  end

  opts.on("-h", "--help", "Prints this message and exists") do
    puts opts
    exit
  end

  opts.on("-v", "--version", "Prints Pastel version") do
    puts Pastel::VERSION
    exit
  end
end

begin
  parser.parse!
rescue OptionParser::ParseError => error
  puts error.message
  exit 1
end

text = STDIN.tty? ? ARGV.pop : $stdin.read

pastel = Pastel.new(**options)

begin
  puts pastel.decorate(text, *ARGV.map(&:to_sym))
rescue Pastel::InvalidAttributeNameError => error
  puts error.message
  exit 1
end
