#!/usr/bin/env ruby

Signal.trap("INT") { exit 1 }

require "pastel"
require "optparse"

options = {}

ARGV << "-h" if ARGV.empty?

parser = OptionParser.new do |opts|
  opts.on("-f", "--force", "Forces string coloring regardless whether terminal supports ANSI escape color sequences or not") do
    options[:enabled] = true
  end

  opts.on("-s", "--styles", "Prints all available color and style names") do
    ops = (ARGV.include?("--force") || ARGV.include?("-f")) ? {enabled: true} : {}
    ops.merge!(options)
    pastel = Pastel.new(**ops)
    puts "Swatch    Name"
    pastel.styles.keys.each do |name|
      next if %i[clear reset].include?(name)
      puts "%s  %s" % [pastel.decorate("◼ pastel", name), name]
    end
    exit
  end

  opts.on("-h", "--help", "Display help") do
    puts opts
    exit
  end
end

begin
  parser.parse!
rescue OptionParser::ParseError => error
  puts error.message
  exit 1
end

text = STDIN.tty? ? ARGV.pop : $stdin.read

pastel = Pastel.new(**options)

begin
  puts pastel.decorate(text, *ARGV.map(&:to_sym))
rescue Pastel::InvalidAttributeNameError => error
  puts error.message
  exit 1
end
