---
name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - "man/**"
      - "*.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "man/**"
      - "*.md"
jobs:
  tests:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.0"
          - "2.1"
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - ruby-head
          - jruby-9.2
          - jruby-9.3
          - jruby-9.4
          - jruby-head
          - truffleruby-head
        include:
          - ruby: "2.2"
            os: ubuntu-20.04
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        shell: 'script -qec "bash {0}"'
        run: bundle exec rake ci
